_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.7
        t:
            "2":
                - 5
                - 53
            "3":
                - 2
                - 55
            "4": 3.12.7
            "5": 0.20.1
            "8":
                - 1
                - 3
            "12": 0.20.1
            "13": windows-amd64
